"use strict";

const { Router } = require("express");
const { wrap } = require("../../middleware/errorHandler");
const { validate } = require("../../middleware/validate");
const { requireAuth } = require("../../middleware/auth");
const { sendOk } = require("../../utils/http");
const { legalConfig } = require("../../config/legal");
const { aiCompleteBody } = require("../schemas");

function createAiRouter({ openai, usersRepo, audit, rateLimiters }) {
  const router = Router();

  router.post(
    "/complete",
    requireAuth,
    rateLimiters.ai,
    validate({ body: aiCompleteBody }),
    wrap(async (req, res) => {
      await usersRepo.recordAcceptance(req.currentUser.id, {
        documentType: "ai_processing_notice",
        documentVersion: req.body.acceptedAiNoticeVersion || legalConfig.aiNoticeVersion,
        acceptanceKind: "acknowledgement",
      });
      const result = await openai.complete({
        prompt: req.body.prompt,
        requestId: req.requestId,
      });
      await audit.record(req, "ai.complete", { model: result.model });
      sendOk(res, {
        output: result.text,
        model: result.model,
        generated: true,
        notice: "This output is generated by an AI system and may be incorrect.",
      });
    })
  );

  return router;
}

module.exports = { createAiRouter };
